### ISSUE TITLE
Savegame time increases a lot after adding this mod

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/DynamicTextProps#14]
After I added this mod to my game (added local and global configurations to transport vehicles), my savegames save time increases hugely. Previousl the game managed to save in less than a minute, now it takes more than 5 minutes. I have not changed almost anything else in the savegame.

**Comment by GameBurrow** [comment]
It seems somewhat workaround is to only save as global, delete local after edit. Then it reduces a lot.

**Comment by klyte45** [comment]
This may happen depending on your PC specs, once adding city layouts will raise the savegame file and also the memory used to pack the savegame file. There's not so much to do about this... May be reconsidered if a bug evidence be found.
