### ISSUE TITLE
Place to list, suggest user submission

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/DynamicTextProps#22]
Currently you have a link for your few examples of WTS vehicle configs but I thought it would be neat to have place were you could list user submittions of WTS configs. For example I made this backup git for myself for my configs:  https://gitlab.com/GameBurrow/wts-vehicles

**Comment by klyte45** [comment]
Other repositories links are welcome. I guess a wiki page would be appropriate to list them. 

Feel free to send a page proposal there. After it could be added to the Workshop description too.

**Comment by GameBurrow** [comment]
It seems Github does not support pull requests to wiki and no place to suggest changes also. So I made a clone and made something up on a fork:
https://github.com/GameBurrow/WriteTheSigns/wiki/Community-Submittions

Markdown for the page:
```
# Community submittions

Here you can find a list of community made Write The Signs configurations. To submit your configuration create an issue to request your addition!

## Vehicles

### Front destination displays for various workshop Buses, Trolleys & Trams

> Focusing mostly on EU buses like MAN, MB, Solaris, Scania, VDL. Vehicles are being added on the run as I use them myself. I was a bit lazy and only added destination displays to the front of the vehicles, not to the sides and back as that would have taken way too long.

- **Link:** https://gitlab.com/GameBurrow/wts-vehicles
- **Author:** GameBurrow

## Buildings

Nothing submitted here yet, be first!

## Other

Nothing submitted here yet, be first!
```

**Comment by klyte45** [comment]
Page created at wiki: https://github.com/klyte45/WriteTheSigns/wiki/Community-Submittions

I opened the editing in the wiki for everyone, so you may be able to edit the pages now.

**Comment by klyte45** [comment]
I will leave this issue pinned because it can be useful for who wants to share their content.
