### ISSUE TITLE
Black letters when zooming in

### ISSUE THREAD

**Issue by wjhunt78** [klyte45/DynamicTextProps#29]
Sorry for spamming you with so many issues :-) But this one is kind of strange.

When zooming in, some letters on vehicles' destination boards go black. In settings, your suggestion is to raise the initial texture size. But while this does not work for me, what does work is to randomly change the font quality. All the black letters are gone then. I can even change the value back to the previous one after that and everything is still fine then. It seems like changing the font quality performs some kind of initialization or resetting which fixes the black letters.

It is nice to be able to fix it this way in the options, but I would rather see the problem did not occur at all. Anything that can be done about this?

By the way... as you might have seen in my screenshots in other threads, I have severe text rendering issues on street names etc.  I know this is not the fault of your mods, but do you know anything that can be done to fix this?

**Comment by klyte45** [comment]
For the black letters, it already have a solution in game, just raise the initial texture value: 
![image](https://user-images.githubusercontent.com/11671356/118477383-0013dd80-b6e5-11eb-93e3-fff448925bdf.png)

The text rendering issues are partially caused by my mods. I'm trying to do something about it

**Comment by wjhunt78** [comment]
Thank you for your response Klyte! I already knew about raising the initial texture size as I wrote in my previous post, but that does not seem to do anything for me opposed to changing font quality randomly. 

Could it be that raising initial texture size only works when done before loading the game? Then it is my bad that I have only done it after the black letters appear.

**Comment by klyte45** [comment]
Sorry, I was in a hurry 😅
Yep, you need to reload the game after doing it.
