### ISSUE TITLE
Mod not loaded after restarting

### ISSUE THREAD

**Issue by stormykara** [klyte45/DynamicTextProps#35]
Hello,

I recently downloaded this mod, loaded my savegame, quit to desktop, then reloaded my savegame. However, I still get this message:
"THIS IS NOT AN ERROR!!!!!!!!
Seems the mod "Write The Signs" was not completely loaded. Restart your game to make it be full loaded!
THIS IS NOT AN ERROR!!!!!!!!"

I've opened the mod folder via the mod settings, and all the folders are there, but they seem to be empty.

What can I do to make the mod fully loaded? Thank you.

**Comment by klyte45** [comment]
Just ignore it. It will work in game anyway. This alert is broken... If not, just reopen this issue.

Anyway, all folder will be empty at beginning, it's the normal scenario.
