### ISSUE TITLE
[Bug] Interruptions of Line Full Name and Line Identifier String

### ISSUE THREAD

**Issue by YuLun-bili** [klyte45/DynamicTextProps#43]
After the most recent update of mods and game, two of transport line elements are interrupted and cannot display correctly.

Originally, the screen on bus should say similar as below:
`R1 Deane Harbor`
`via Deane Int'change`

However, now they're displaying as the screenshot
(Identifier becomes line full name and line full name is an empty string)

![20220126214727_1](https://user-images.githubusercontent.com/70589524/151253682-ff16e844-230b-4dfc-bb09-44155baa7b2a.jpg)

here's another screenshot took before Jan 25 and displays correctly

![20220118192437_1](https://user-images.githubusercontent.com/70589524/151254328-908b563e-0676-43df-9ef9-9441c5d0a1bf.jpg)

**Comment by PC28K** [comment]
I'm experiencing the same thing

**Comment by UpLift-Vancouver** [comment]
I too have run into the same problem...
![WTS_sign_bug](https://user-images.githubusercontent.com/96807016/151792031-35d47c87-d700-4366-99fd-67fea8c776e5.png)

**Comment by klyte45** [comment]
I'll try to make a WTS update later this week, and I hope there's a fix for this.
