### ISSUE TITLE
Cannot display non-English characters in text display

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/DynamicTextProps#45]
For example:

![WTS-Test-01](https://user-images.githubusercontent.com/17726797/182063918-dda17201-907d-4919-863a-7e6c2e723736.png)

It was supposed to display "機場 (東) 240X" as destination string with TLM, but it could not, and only the () remains on the left side.

**Comment by klyte45** [comment]
May the font not support these characters, so nothing will be shown. It's not the same of game font there.
Try installing manually a font in WTS fonts folder and try it again. The default font have a lot of characters but certainly have not sufficient characters for some scripts
