### ISSUE TITLE
not seeing road segment tab for placing signs

### ISSUE THREAD

**Issue by VirtualGaming1** [klyte45/DynamicTextProps#46]
![image](https://user-images.githubusercontent.com/20447403/184717859-69bec38d-9d81-480d-9127-900e6e44677b.png)

So I am not able to find the road segment tab where I could place the highway signs that I want to place. been a while since I played. did this got changed or is this a bug?

**Comment by klyte45** [comment]
This mod will have a overhaul in next months with most recent development techniques from modding community, as the current code is very old and hard to maintain nowadays

Expect for a completely new mod in some months
