### ISSUE TITLE
Is this mod dead or what? No responds and last update was in Feb.

### ISSUE THREAD

**Issue by VirtualGaming1** [klyte45/DynamicTextProps#47]
So There have been no Responds for 2 of the issues
https://github.com/klyte45/WriteTheSigns/issues/46
https://github.com/klyte45/WriteTheSigns/issues/45

Last Responds from Klyte was in January 16th. that is getting close to be 8 months. And on the steam page the mod was not updated since February 15th

**Comment by klyte45** [comment]
Responded at #46
